version: '3.8'

services:
  web:
    build: .
    networks:
      - ssti
    environment:
      - DB_HOST=db
      - DB_USER=sqluser
      - DB_PASSWORD=Wm!$5d4*@2!6s9
      - DB_NAME=notes_app
    depends_on:
      - db
    restart: always
    expose:
      - 5000
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=5$NK*35%*4p*4H
      - MYSQL_DATABASE=notes_app
      - MYSQL_USER=sqluser
      - MYSQL_PASSWORD=Wm!$5d4*@2!6s9
    networks:
      - ssti
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "10.0.0.1:8002:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - ssti

volumes:
  static:
  db:

networks:
  ssti:
