version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=baho
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    networks:
      - sqli
    expose:
      - 5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://baho:secret@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - backend:/app
    restart: always
    networks:
      - sqli

volumes:
 backend:

networks:
  sqli:

