version: '3.8'

services:
  backend:
    build:
      context: ./jwt-ctf-backend
      dockerfile: Dockerfile
    ports:
      - "7106:7106"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped

  frontend:
    build:
      context: ./jwt-ctf-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped