version: '3.8'

services:
  backend:
    build:
      context: ./jwt-ctf-backend
      dockerfile: Dockerfile
    expose:
      - 7106
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - jwt-amd

  frontend:
    build:
      context: ./jwt-ctf-frontend
      dockerfile: Dockerfile

    expose:
      - 80
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - jwt-amd


networks:
  jwt-amd:

